// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JokeMoke.Shared
{
    public partial class JokeStatisticsLogs
    {
        public Guid Id { get; set; }
        public byte? LogType { get; set; }
        public DateTime CreatedAt { get; set; }
        public Guid CreatedBy { get; set; }
        public Guid JokeStatisticsId { get; set; }

        public virtual User CreatedByNavigation { get; set; }
        public virtual JokeStatistics JokeStatistics { get; set; }
    }
}