// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JokeMoke.Shared
{
    public partial class JokeStatistics
    {
        public int Id { get; set; }
        public int JokeId { get; set; }
        public int LikeCount { get; set; }
        public int DislikeCount { get; set; }

        public virtual Joke Joke { get; set; }
    }
}