// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JokeMoke.Shared
{
    public partial class JokeType
    {
        public JokeType()
        {
            Joke = new HashSet<Joke>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Joke> Joke { get; set; }
    }
}