// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JokeMoke.Shared
{
    public partial class User
    {
        public User()
        {
            Joke = new HashSet<Joke>();
        }

        public int Id { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int RoleId { get; set; }
        public string ProfilePicUrl { get; set; }

        public virtual Role Role { get; set; }
        public virtual ICollection<Joke> Joke { get; set; }
    }
}